#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinWifiCarApp.Resource", IsApplication=true)]

namespace XamarinWifiCarApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int sym_backward = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int sym_backward_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sym_forward = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int sym_forward_1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sym_left = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sym_left_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sym_right = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sym_right_1 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sym_stop = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int sym_stop_1 = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int imageButtonBackward = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int imageButtonForward = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int imageButtonLeft = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int imageButtonRight = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int imageButtonStop = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int textMensaje = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int videoView1 = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int muestraElTexto = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
